title: Matthew Dudak
url: "https://mjdudak.com"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

remote_theme: ankitsultana/researcher@gem

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Projects"
   link: "projects"


